import CommitteeEvent from './CommitteeEvent';
import { committees, attendanceTypes } from './utils.js';

let eventData = [
  new CommitteeEvent({
    eventName: 'Cool ACM Committee Event tree frog dog',
    committee: committees.acm,
    date: new Date(2021, 3, 26),
    isTrack: true,
    sessionNumber: 2,
    attendanceType: attendanceTypes.hybrid,
    physicalLocation: 'Boelter Hall',
    virtualLocation: 'https://www.uclaacm.com',
    eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
    contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
    tags: ['cool', 'general', 'fun'],
    teachers: ['John Smith', 'Bob Jones']}),
  new CommitteeEvent({
    eventName: 'Cool ACM Committee Event frog man bat',
    committee: committees.w,
    date: new Date(2017, 11, 5),
    isTrack: true,
    sessionNumber: 2,
    attendanceType: attendanceTypes.hybrid,
    physicalLocation: 'Boelter Hall',
    virtualLocation: 'https://www.uclaacm.com',
    eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
    contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
    tags: ['cool', 'general', 'fun'],
    teachers: ['John Smith', 'Bob Jones']}),
  new CommitteeEvent({
    eventName: 'Cool ACM Committee Event dog',
    committee: committees.cyber,
    date: new Date(2018, 1, 4),
    isTrack: true,
    sessionNumber: 2,
    attendanceType: attendanceTypes.hybrid,
    physicalLocation: 'Boelter Hall',
    virtualLocation: 'https://www.uclaacm.com',
    eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
    contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
    tags: ['cool', 'general', 'fun'],
    teachers: ['John Smith', 'Bob Jones']}),
  new CommitteeEvent({
    eventName: 'Cool ACM Committee Event man frog',
    committee: committees.icpc,
    date: new Date(2021, 3, 26),
    isTrack: false,
    sessionNumber: 2,
    attendanceType: attendanceTypes.hybrid,
    physicalLocation: 'Boelter Hall',
    virtualLocation: 'https://www.uclaacm.com',
    eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
    contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
    tags: ['cool', 'general', 'fun'],
    teachers: ['John Smith', 'Bob Jones']}),
  new CommitteeEvent({
    eventName: 'Cool ACM Committee Event tree pine',
    committee: committees.hack,
    date: new Date(2021, 3, 26),
    isTrack: false,
    sessionNumber: 2,
    attendanceType: attendanceTypes.hybrid,
    physicalLocation: 'Boelter Hall',
    virtualLocation: 'https://www.uclaacm.com',
    eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
    contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
    tags: ['cool', 'general', 'fun'],
    teachers: ['John Smith', 'Bob Jones']})
];

export default eventData;