import CommitteeEvent from './CommitteeEvent';

let eventData = [
  new CommitteeEvent({
      eventName: 'Cool ACM Committee Event',
      committee: 'Internal Board',
      date: new Date(2021, 4, 26),
      isTrack: true,
      sessionNumber: 2,
      attendanceType: 'hybrid',
      physicalLocation: 'Boelter Hall',
      virtualLocation: 'https://www.uclaacm.com',
      eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
      contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
      tags: ['cool', 'general', 'fun'],
      teachers: ['John Smith', 'Bob Jones']}),
      new CommitteeEvent({
        eventName: 'Cool ACM Committee Event',
        committee: 'Internal Board',
        date: new Date(2021, 4, 26),
        isTrack: true,
        sessionNumber: 2,
        attendanceType: 'hybrid',
        physicalLocation: 'Boelter Hall',
        virtualLocation: 'https://www.uclaacm.com',
        eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
        contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
        tags: ['cool', 'general', 'fun'],
        teachers: ['John Smith', 'Bob Jones']}),
        new CommitteeEvent({
          eventName: 'Cool ACM Committee Event',
          committee: 'Internal Board',
          date: new Date(2021, 4, 26),
          isTrack: true,
          sessionNumber: 2,
          attendanceType: 'hybrid',
          physicalLocation: 'Boelter Hall',
          virtualLocation: 'https://www.uclaacm.com',
          eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
          contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
          tags: ['cool', 'general', 'fun'],
          teachers: ['John Smith', 'Bob Jones']}),
          new CommitteeEvent({
            eventName: 'Cool ACM Committee Event',
            committee: 'Internal Board',
            date: new Date(2021, 4, 26),
            isTrack: true,
            sessionNumber: 2,
            attendanceType: 'hybrid',
            physicalLocation: 'Boelter Hall',
            virtualLocation: 'https://www.uclaacm.com',
            eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
            contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
            tags: ['cool', 'general', 'fun'],
            teachers: ['John Smith', 'Bob Jones']}),
            new CommitteeEvent({
              eventName: 'Cool ACM Committee Event',
              committee: 'Internal Board',
              date: new Date(2021, 4, 26),
              isTrack: true,
              sessionNumber: 2,
              attendanceType: 'hybrid',
              physicalLocation: 'Boelter Hall',
              virtualLocation: 'https://www.uclaacm.com',
              eventLinks: [{'link': 'https://www.facebook.com', 'title': 'Facebook'}, {'link': 'https://calendar.google.com', 'title': 'Google Calendar'}],
              contentLinks: [{'link': 'https://slides.google.com', 'title': 'Google Slides'}, {'link': 'https://www.youtube.com', 'title': 'YouTube'}],
              tags: ['cool', 'general', 'fun'],
              teachers: ['John Smith', 'Bob Jones']})
];

export default eventData;