export default [
	{
		name: 'Studio',
		class: 'studio',
		tagline: 'Creative Expression through Games and VR',
		image: '/images/committees/logo-studio.svg',
		links: {
			main: 'https://www.facebook.com/groups/uclaacmstudio',
			facebook: 'https://www.facebook.com/groups/uclaacmstudio',
			discord: 'https://discord.gg/9jDH6rN',
		},
		introImage: '/images/committees/placeholder.png',
		mission: 'Our mission is to teach skills revolving around video game development such as computer science, game design and art in order to help usher students into the game development industry.',
	},
	{
		name: 'ICPC',
		class: 'icpc',
		tagline: 'Mastering Algorithms and Competitive Programming',
		image: '/images/committees/logo-icpc.svg',
		links: {
			main: 'https://www.facebook.com/groups/ucla.icpc',
			facebook: 'https://www.facebook.com/groups/ucla.icpc/',
			email: 'uclaicpc@gmail.com',
		},
		introImage: '/images/committees/placeholder.png',
		mission: 'To promote algorithmic thinking and help build proficient problem solvers.',
	},
	{
		name: 'Design',
		class: 'design',
		tagline: 'Form Follows Function',
		image: '/images/committees/logo-design.svg',
		links: {
			main: 'https://www.facebook.com/groups/acmdesign/',
			facebook: 'https://www.facebook.com/groups/acmdesign',
			styleguide: 'https://design.uclaacm.com/',
		},
		introImage: '/images/committees/placeholder.png',
		mission: 'Our mission is to design, manage, and support the visual identity of ACM at UCLA. We create the club\'s branding, event banners, and more elements, while also doing workshops to teach UI/UX to the UCLA community.',
	},
	{
		name: 'Cyber',
		class: 'cyber',
		tagline: 'Cybersecurity Made Simple',
		image: '/images/committees/logo-cyber.svg',
		links: {
			main: 'https://acmcyber.com/',
			discord: 'https://discord.gg/j9dgf2q',
			website: 'https://acmcyber.com/',
			facebook: 'https://www.facebook.com/groups/320869398280511',
			email: 'uclacyber@gmail.com',
		},
		introImage: '/images/committees/placeholder.png',
		mission: 'Our mission is to create a community in which both experts and beginners alike can grow in the field of cybersecurity skills and knowledge. We want to make cybersecurity simple and accessible for everyone. To that end, we hold workshops and special events designed for beginners with no experience or just beginning in cybersecurity.',
	},
	{
		name: 'Teach LA',
		class: 'teachla',
		tagline: 'Learn It, Teach It',
		image: '/images/committees/logo-teachla.svg',
		links: {
			main: 'https://teachla.uclaacm.com',
			website: 'https://teachla.uclaacm.com ',
			facebook: 'https://www.facebook.com/teachlaucla/',
		},
		introImage: '/images/committees/placeholder.png',
		mission: 'Our mission is to provide equal access to K-12 CS education in the Los Angeles area. We do this by teaching classes, running workshops and events, and writing software!',
	},
	{
		name: 'W',
		class: 'w',
		tagline: 'Starting Conversations about Diversity in Tech',
		image: '/images/committees/logo-w.svg',
		links: {
			main: 'https://www.facebook.com/groups/uclaacmw',
			facebook: 'https://www.facebook.com/groups/uclaacmw',
		},
		introImage: '/images/committees/placeholder.png',
		mission: 'Our goal is to promote diversity in tech through mentorship, networking, and professional development opportunities. We’re a safe space for everyone interested in computer science. :)',
	},
	{
		name: 'AI',
		class: 'ai',
		tagline: 'Learning Machine Learning',
		image: '/images/committees/logo-ai.svg',
		links: {
			main: 'https://uclaacmai.github.io/',
			facebook: 'https://www.facebook.com/groups/uclaacmai',
			website: 'https://uclaacmai.github.io/',
			instagram: 'https://www.instagram.com/acm_ai_ucla/',
			twitter: 'https://twitter.com/acm_ai_ucla',
			github: 'https://github.com/uclaacmai',
		},
		introImage: '/images/committees/placeholder.png',
		mission: 'ACM AI’s mission is to grow and develop a community of students interested in Artificial Intelligence (AI) at UCLA, Los Angeles, and beyond. Our initiatives aim to serve everyone who has an interest in AI regardless of background, including people with no prior experience or knowledge in AI and non-CS majors.',
	},
	{
		name: 'Hack',
		class: 'hack',
		tagline: 'Move Fast, Build Things',
		image: '/images/committees/logo-hack.svg',
		links: {
			main: 'https://hack.uclaacm.com',
			facebook: 'https://hack.uclaacm.com/',
			website: 'https://www.facebook.com/groups/acmhack',
			instagram: 'https://www.instagram.com/uclahack',
		},
		introImage: '/images/committees/placeholder.png',
		mission: 'To empower the community by providing the means to build amazing things and explore what is possible through code!',
	}
]
