export default [
    {
        date: '01/27/21',
        headline: '"You Belong in AI": the ACM AI podcast aims to make computer science more diverse, accessible',
        image: '/images/ybAI_podcast.png',
        alt: 'Podcast Cover for "You belong in AI"!',
        link: 'https://dailybruin.com/2021/01/27/student-run-tech-podcast-aims-to-make-computer-science-more-diverse-accessible',
    },
    {
        date: '07/21/20',
        headline: 'BruinLabs: A product development summer program by Bruin Entrepreneurs, DevX, and ACM',
        image: '/images/bruinlabs.png',
        alt: 'BruinLabs Collaborative Program',
        link: 'https://samueli.ucla.edu/bruinlabs-ucla-clubs-offers-free-program-to-teach-product-development-skills/',
    },
    {
        date: '05/28/20',
        headline: 'Engineering Student Orgs Adapt to Virtual Spring Quarter',
        image: '/images/virtualclub.jpg',
        alt: 'ACM UCLA Virtual Zoom Meeting',
        link: 'https://samueli.ucla.edu/engineering-student-clubs-adapt-to-a-virtual-spring-quarter/',
    },
    {
        date: '05/15/20',
        headline: '2019–20 Student Chapter Excellence Award',
        image: '/images/2020-acm-excellence-award.png',
        alt: '2019-2020 Student Chapter Excellence Award',
        link: 'https://samueli.ucla.edu/ucla-student-club-honored-by-worlds-largest-educational-and-scientific-computing-society/',
    },
    {
        date: '05/05/20',
        headline: 'Tech Gala 2020 showcases top Bruin CS projects',
        image: '/images/tech-gala.jpg',
        alt: 'ACM Tech Gala Banner',
        link: 'https://samueli.ucla.edu/tech-gala-recognizes-top-student-computer-science-projects/',
    },
    {
        date: '11/19/19',
        headline: 'ICPC Qualifies for 2020 North American Championship',
        image: '/images/icpc_natls_2020.jpg',
        alt: 'ICPC members celebrating victory!',
        link: 'https://www.cs.ucla.edu/cs-undergraduate-students-win-4th-in-icpc-southern-california-regionals/',
    },
    {
        date: '06/04/18',
        headline: '2017–18 Student Chapter Excellence Award',
        image: '/images/2018-acm-excellence-award.png',
        alt: '2017-2018 Student Chapter Excellence Award',
        link: 'https://www.cs.ucla.edu/ucla-acm-upe-receive-chapter-excellence-awards/',
    },
    {
        date: '05/24/17',
        headline: '2016–17 Student Chapter Excellence Award',
        image: '/images/2017-acm-excellence-award.png',
        alt: '2016-2017 Student Chapter Excellence Award',
        link: 'https://www.cs.ucla.edu/ucla-acm-receives-student-chapter-excellence-award/',
    },
];
